server:
  port: 7000
spring:
  application:
    name: 7000-gateway

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # 注册中心地址

    gateway:
      discovery:
        locator:
          enabled: true # 让gateway可以发现Nacos中的微服务

      routes: #路由数组
        # 路由一
        - id: issue # 路由对象的ID
          uri: lb://8082-issue # lb：指定微服务名，并负载均衡，
          order: 1 # 路由的优先级
          predicates: # 断言
            - Path=/issue/** # 当请求路径包含issue，转发到8082
          filters: # 过滤器
            - StripPrefix=1 #在转发之前去掉几层路径
