server:
  port: 8086

spring:
  application:
    name: answer-search-8086
  profiles:
    active: dev #默认为开发环境


mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
