spring:
  application:
    name: answer-search-8086
  profiles:
    active: dev #默认为开发环境

server:
  port: 8086

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml