server:
  port: 3344

spring:
  application:
    name: springcloud-config-server-3344
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:3344
    config:
      server:
        git:
          uri: https://gitee.com/jizhideluyi/springcloud-config.git
          default-label: master